# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: dctna-server

before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0

builds:
  - id: binary
    dir: cmd/dctna-server
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 8
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}
    env:
      - CGO_ENABLED=0

archives:
  - id: archive
    format: tar.gz
    replacements:
      darwin: macOS
    files:
      - LICENSE*
      - README*
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "philipssoftware/{{ .ProjectName }}:{{ .Tag }}"
      - "philipssoftware/{{ .ProjectName }}:v{{ .Major }}"
      - "philipssoftware/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "philipssoftware/{{ .ProjectName }}:latest"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Major }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.licenses=MIT"
      - "--label=org.opencontainers.image.vendor=Koninklijke Philips N.V."
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=DATE={{ .Date }}"
      - "--build-arg=COMMIT={{ .ShortCommit }}"
    extra_files:
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "lib"
      - "certs"
      - ".notary"
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  prerelease: auto
