version: "2.0"
services:
  dctna-web:
    image: dctna-web
    build: web
    ports:
      - "3000:80"
    environment:
      DCTNA_API: https://dctna-server:8443
    depends_on:
      - dctna-server
    networks:
      - sig
  dctna-server:
    image: dctna-server
    build:
      context: .
      dockerfile: server.Dockerfile
    networks:
      - sig
    ports:
      - "8086:8086"
      - "8443:8443"
    volumes:
      - dct_data:/root/.docker/trust

volumes:
  dct_data:
    external: false
networks:
  sig:
    external: false
