@startuml

!$authors = "Marco Franssen"

title DCTNA Deployment Architecture
center header Author: $authors
center footer Author: $authors

skinparam sequence {
	ArrowColor black
	ActorBorderColor DeepSkyBlue
	LifeLineBorderColor black
	LifeLineBackgroundColor grey
}

skinparam component<<dctna>> {
  BackgroundColor lightblue
  BorderColor blue
}

skinparam component<<notary>> {
  BackgroundColor lightgreen
  BorderColor green
}

skinparam actor {
  BackgroundColor lightgrey
  BorderColor black
}

skinparam database {
  BackgroundColor lightgrey
  BorderColor black
}

skinparam database<<notary>> {
  BackgroundColor lightgreen
  BorderColor green
}

skinparam component {
  BackgroundColor lightgrey
  BorderColor black
}

actor "Docker Trust Admin" as Admin
actor "CI Job" as CiJob

database ServerDB <<notary>> [
    server-db
]
database SignerDB <<notary>> [
    signer-db
]

[dctna-web] <<dctna>>
[dctna-server] <<dctna>>
[notary-signer] <<notary>>
[notary-server] <<notary>>

CiJob ..> [docker-cli] : sign docker image\nand push to registry
[docker-cli] ..> [docker-registry] : push/pull\nimages
[docker-cli] ..> [notary-server] : sign image /\nfetch tuf metadata
Admin ..> [dctna-web] : administer docker repositories\nand delegations
[dctna-web] ..> [dctna-server] : rest api
[dctna-server] .right.> [vault] : stores passphrases\nfor keys
[dctna-server] ..> [notary-server]

[notary-server] .left.> [notary-signer]
[notary-server] ..> [ServerDB]
[notary-signer] ..> [SignerDB]

@enduml
