name: CI

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1.0.0
      with:
        version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.0.0

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

    - name: Test and Cover
      run: go test -v -race -count=1 -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: true
