name: CI

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

    - name: Build sandbox
      run: |
        (cd notary ; make cross)
        docker-compose -f notary/docker-compose.sandbox.yml build

    - name: Run sandbox
      run: docker-compose -f notary/docker-compose.sandbox.yml up -d

    - name: Wait for sandbox to boot
      run: sleep 30

    - name: Test and Cover
      run: go test -v -race -count=1 -covermode=atomic -coverprofile=coverage.out ./...

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: true

    - name: Shutdown sandbox
      run: docker-compose -f notary/docker-compose.sandbox.yml down
